---
name: Checks

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: docker compose --version

      - name: Build containers
        run: docker compose build

      - name: Test
        run: docker compose run --rm app sh -c "python manage.py test"
        timeout-minutes: 10

      - name: Lint
        run: docker compose run --rm app sh -c "flake8"
        timeout-minutes: 5


